In [1]:
import pandas as pd
import numpy as np

In [2]:
dic1 = {
    "name" : ['Sudip','Sayan','Patra','Debnath'],
    "marks" : [70,90,82,85],
    "city" : ['Chengail','Chengail','Beltala','SaratPalli']
}

In [3]:
df = pd.DataFrame(dic1)

In [4]:
df.to_csv('details.csv')

In [5]:
df.to_csv('False_index.csv',index=False)

In [6]:
df.head(2)

name  marks      city
0  Sudip     70  Chengail
1  Sayan     90  Chengail

In [7]:
df.tail(1)

name  marks        city
3  Debnath     85  SaratPalli

In [8]:
df.describe()

marks
count   4.00
mean   81.75
std     8.50
min    70.00
25%    79.00
50%    83.50
75%    86.25
max    90.00

In [9]:
friends = pd.read_csv('friends.csv')

In [10]:
friends


Roll   Name Sec
0     1  Sayan   A
1     2  Sohan   B
2     3    Ram   C
3     4  Sudip   A

In [11]:
friends ['Sec'][3] = 'A'

C:\Users\Sudip\AppData\Local\Temp\ipykernel_4452\3771689511.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  friends ['Sec'][3] = 'A'


In [12]:
friends.to_csv('friends.csv',index = False)


In [13]:
friends.index = ['1st','2nd','3rd','4th']

In [14]:
friends


Roll   Name Sec
1st     1  Sayan   A
2nd     2  Sohan   B
3rd     3    Ram   C
4th     4  Sudip   A

In [15]:
friends.index = ['1','2','3','4']

In [16]:
friends

Roll   Name Sec
1     1  Sayan   A
2     2  Sohan   B
3     3    Ram   C
4     4  Sudip   A

In [17]:
#Series 
ser = pd.Series(np.random.rand(20))
# print (ser)
type (ser)

pandas.core.series.Series

In [18]:
# DataFrame
newdf = pd.DataFrame(np.random.rand(5,6),index = np.arange(5))
print (newdf)
print (type(newdf))
newdf.dtypes

          0         1         2         3         4         5
0  0.181351  0.100993  0.192047  0.255966  0.502766  0.607091
1  0.635242  0.904895  0.089470  0.235473  0.975881  0.388755
2  0.063688  0.711730  0.062845  0.400934  0.018455  0.709325
3  0.887760  0.176901  0.119094  0.228779  0.490193  0.614998
4  0.019880  0.101610  0.154653  0.277430  0.250990  0.940425
<class 'pandas.core.frame.DataFrame'>


0    float64
1    float64
2    float64
3    float64
4    float64
5    float64
dtype: object

In [19]:
arr = np.array(newdf)
print (arr)

[[0.1813513  0.1009927  0.19204712 0.25596577 0.50276556 0.60709129]
 [0.63524215 0.90489468 0.08947049 0.23547257 0.97588131 0.38875495]
 [0.06368812 0.71173014 0.06284459 0.40093384 0.01845532 0.70932455]
 [0.88775954 0.17690054 0.11909392 0.22877876 0.49019263 0.61499755]
 [0.01987962 0.10160976 0.15465328 0.27743036 0.25098979 0.94042509]]


In [20]:
x = newdf.sort_index(axis = 0, ascending = False)
print (x)
newdf.sort_index(axis = 1, ascending = False)

          0         1         2         3         4         5
4  0.019880  0.101610  0.154653  0.277430  0.250990  0.940425
3  0.887760  0.176901  0.119094  0.228779  0.490193  0.614998
2  0.063688  0.711730  0.062845  0.400934  0.018455  0.709325
1  0.635242  0.904895  0.089470  0.235473  0.975881  0.388755
0  0.181351  0.100993  0.192047  0.255966  0.502766  0.607091


5         4         3         2         1         0
0  0.607091  0.502766  0.255966  0.192047  0.100993  0.181351
1  0.388755  0.975881  0.235473  0.089470  0.904895  0.635242
2  0.709325  0.018455  0.400934  0.062845  0.711730  0.063688
3  0.614998  0.490193  0.228779  0.119094  0.176901  0.887760
4  0.940425  0.250990  0.277430  0.154653  0.101610  0.019880

In [21]:
newdf.loc[0][0] = 143  
print (newdf)
print (type(newdf[0]))

            0         1         2         3         4         5
0  143.000000  0.100993  0.192047  0.255966  0.502766  0.607091
1    0.635242  0.904895  0.089470  0.235473  0.975881  0.388755
2    0.063688  0.711730  0.062845  0.400934  0.018455  0.709325
3    0.887760  0.176901  0.119094  0.228779  0.490193  0.614998
4    0.019880  0.101610  0.154653  0.277430  0.250990  0.940425
<class 'pandas.core.series.Series'>


In [22]:
newdf.loc[0][0] = "146"
print (newdf)
print (type(newdf[0]))

            0         1         2         3         4         5
0  143.000000  0.100993  0.192047  0.255966  0.502766  0.607091
1    0.635242  0.904895  0.089470  0.235473  0.975881  0.388755
2    0.063688  0.711730  0.062845  0.400934  0.018455  0.709325
3    0.887760  0.176901  0.119094  0.228779  0.490193  0.614998
4    0.019880  0.101610  0.154653  0.277430  0.250990  0.940425
<class 'pandas.core.series.Series'>


C:\Users\Sudip\AppData\Local\Temp\ipykernel_4452\1954414514.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '146' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf.loc[0][0] = "146"


In [23]:
newdf.columns = list ("ABCDEF")

In [24]:
newdf.loc[(newdf['A']>0.4) & (newdf['C']<0.5)]


A         B         C         D         E         F
0  143.000000  0.100993  0.192047  0.255966  0.502766  0.607091
1    0.635242  0.904895  0.089470  0.235473  0.975881  0.388755
3    0.887760  0.176901  0.119094  0.228779  0.490193  0.614998

In [25]:
newdf.drop(['F'],axis = 1)

A         B         C         D         E
0  143.000000  0.100993  0.192047  0.255966  0.502766
1    0.635242  0.904895  0.089470  0.235473  0.975881
2    0.063688  0.711730  0.062845  0.400934  0.018455
3    0.887760  0.176901  0.119094  0.228779  0.490193
4    0.019880  0.101610  0.154653  0.277430  0.250990

In [28]:
df=pd.read_csv("car.csv")
df

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte